"""Build a LOCAL preview app with a bundled Python runtime. No publication or upload."""
# ruff: noqa: S603 -- fixed build tools and explicit maintainer-owned filesystem arguments

import argparse
import platform
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

from erasure.release import export_source

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--output', type=Path, required=True, help='New .app path; never overwritten')
parser.add_argument('--allow-unlicensed-preview', action='store_true')
args = parser.parse_args()
if sys.platform != 'darwin':
    raise SystemExit('Build this preview on macOS for the target architecture.')
root = Path(__file__).resolve().parents[1]
runtime = Path(sys.base_prefix).resolve()
if not (runtime / 'BUILD').is_file() or not (runtime / 'bin/python3').exists():
    raise SystemExit('Use uv-managed standalone Python to build a relocatable runtime.')
for path in runtime.rglob('*'):
    if path.is_symlink() and not path.resolve().is_relative_to(runtime):
        raise SystemExit('Python runtime has an external symlink; refusing a non-portable package.')
app = args.output.absolute()
if app.suffix != '.app':
    raise SystemExit('Output must end in .app')
app.mkdir(parents=True, exist_ok=False)
resources = app / 'Contents/Resources'
resources.mkdir(parents=True)
export_source(root, resources / 'app', require_license=not args.allow_unlicensed_preview)
shutil.copytree(runtime, resources / 'python', symlinks=True,
                ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
python = resources / 'python/bin/python3'
uv = shutil.which('uv')
if not uv:
    raise SystemExit('The build machine needs uv; end users will not.')
site_packages = resources / 'python/lib' / f'python{sys.version_info.major}.{sys.version_info.minor}' / 'site-packages'
subprocess.run([uv, 'pip', 'install', '--python', str(python), '--target', str(site_packages), '--require-hashes', '--no-deps',
                '-r', str(root / 'requirements.lock')], check=True)
macos = app / 'Contents/MacOS'
macos.mkdir()
subprocess.run(['/usr/bin/clang', '-fobjc-arc', '-framework', 'Cocoa',
                str(root / 'macos/Launcher.m'), '-o', str(macos / 'erase')], check=True)
info = {
    'CFBundleExecutable': 'erase', 'CFBundleIdentifier': 'local.erase.desktop',
    'CFBundleName': 'erase', 'CFBundleDisplayName': 'erase', 'CFBundlePackageType': 'APPL',
    'CFBundleShortVersionString': '0.1.0', 'CFBundleVersion': '1',
    'LSMinimumSystemVersion': '13.0', 'NSHighResolutionCapable': True,
    'NSAppleEventsUsageDescription': 'erase asks you to choose a password for your local dashboard.',
}
(app / 'Contents/Info.plist').write_bytes(plistlib.dumps(info))
subprocess.run([str(python), '-I', '-B', '-c', 'import fastapi, nacl, sqlalchemy, uvicorn; print("Bundled runtime imports passed")'], check=True)
# Only this newly-created artifact is touched. Installer-generated bytecode would
# leak build paths and runtime writes would invalidate the sealed app signature.
for cache in app.rglob('__pycache__'):
    if cache.is_dir() and not cache.is_symlink():
        shutil.rmtree(cache)
subprocess.run(['/usr/bin/codesign', '--force', '--deep', '--sign', '-', str(app)], check=True)
subprocess.run(['/usr/bin/codesign', '--verify', '--deep', '--strict', str(app)], check=True)
print(f'Local {platform.machine()} preview built: {app}')
print('Ad-hoc signed only, NOT notarized. Do not distribute as a verified desktop release.')
